/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author PABLO
 */
public class TelaInicial extends javax.swing.JFrame {

        /**
         * Creates new form TelaInicial
         */
        public TelaInicial() {
                initComponents();
                //setExtendedState(MAXIMIZED_BOTH); 
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jMenu1 = new javax.swing.JMenu();
                jMenuBar1 = new javax.swing.JMenuBar();
                jMenu2 = new javax.swing.JMenu();
                mnCadastrarDono = new javax.swing.JMenuItem();
                mnCadastrarAnimal = new javax.swing.JMenuItem();
                jMenu3 = new javax.swing.JMenu();

                jMenu1.setText("jMenu1");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Clinica Veterinaria");

                jMenu2.setText("Cadastro");

                mnCadastrarDono.setText("Dono");
                mnCadastrarDono.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mnCadastrarDonoActionPerformed(evt);
                        }
                });
                jMenu2.add(mnCadastrarDono);

                mnCadastrarAnimal.setText("Animal");
                mnCadastrarAnimal.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mnCadastrarAnimalActionPerformed(evt);
                        }
                });
                jMenu2.add(mnCadastrarAnimal);

                jMenuBar1.add(jMenu2);

                jMenu3.setText("Suporte");
                jMenuBar1.add(jMenu3);

                setJMenuBar(jMenuBar1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1027, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 595, Short.MAX_VALUE)
                );

                setSize(new java.awt.Dimension(1043, 655));
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void mnCadastrarDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarDonoActionPerformed
                // TODO add your handling code here:
                FrmCadastrarDono cadastrarDono = new FrmCadastrarDono();
                cadastrarDono.setVisible(true);
        }//GEN-LAST:event_mnCadastrarDonoActionPerformed

        private void mnCadastrarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarAnimalActionPerformed
                // TODO add your handling code here:
                FrmCadastrarAnimal cadastrarAnimal = new FrmCadastrarAnimal();
                cadastrarAnimal.setVisible(true);
        }//GEN-LAST:event_mnCadastrarAnimalActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
        //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new TelaInicial().setVisible(true);
                                
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JMenu jMenu1;
        private javax.swing.JMenu jMenu2;
        private javax.swing.JMenu jMenu3;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JMenuItem mnCadastrarAnimal;
        private javax.swing.JMenuItem mnCadastrarDono;
        // End of variables declaration//GEN-END:variables
}
